# Although psptoolchain is not using GitLab, I'm considering creating a mirror
# on GitLab and the GitLab CI is by far the most powerful. I will be using this
# to run tests, at least locally before committing.
---
image: topsekretpl/psptoolchain-ci:latest

stages:
        - build

build-psptoolchain:
        stage: build
        script:
                - dash ./toolchain-local.sh -j 4
                # Use pigz for performance reasons
                # When I tried to use xz -6e, I got timeout because of the
                # compression (sic!)
                - tar cv pspdev | pigz -5 -p4 > pspdev.tar.gz
        artifacts:
                paths:
                        - pspdev.tar.gz
