name: CI-Docker

on:
  push:
    branches:
      - master
      - toolchain-only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        tags: latest
        tag_with_ref: true
        add_git_labels: true

    - name: Send compile action
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: pspdev/pspsdk
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: run_build
        client-payload: '{"ref": "${{ github.ref }}"}'
